### ISSUE TITLE
[string "gamedata/alldefs_post.lua"]:159: attempt to perform arithmetic on a string value

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#87] opened 2017-12-31 07:25 UTC
from springlobby.log:
2017-12-31 07:28:52.066 Warning /data/private/buildbot/slaves/springlobby/develop-win/build/src/log.cpp:215 Unitsync: Balanced Annihilation V10.02 ProcessUnits: luaParser.Execute() failed: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/weaponDefs.lua, error = 2, gamedata/weapondefs_post.lua, [string "gamedata/alldefs_post.lua"]:159: attempt to perform arithmetic on a string value

**Comment by ForbodingAngel** [comment] 2018-01-01 04:25
Fixed in https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/18949fdaceef577ccb14868df6d5808d36f929e0

Caused by instances of weapondefs having strings for edgeeffectiveness instead of ints.
I.E.:
edgeEffectiveness = "1",

**Closed by ForbodingAngel** 2018-01-01 04:25 UTC
