### ISSUE TITLE
luamex design stuff

### ISSUE THREAD

**Issue by sprunk** [Balanced-Annihilation/Balanced-Annihilation#19] opened 2017-01-17 13:06 UTC
What happens when an areamex command is given to a group of cons whose mex types conflict?

**Comment by ForbodingAngel** [comment] 2017-01-17 13:22
I would say simply use the first builder returned in the group.

**Comment by ForbodingAngel** [comment] 2017-01-20 01:29
https://i.imgur.com/kC9Ibas.png
Mex numbers are on the wrong plane :-)

**Comment by ForbodingAngel** [comment] 2017-01-20 02:24
`[f=0014170] Error in Update(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:496: attempt to perform arithmetic on local 'cmd_id' (a nil value)`

if not mexDefID[-cmd_id] then

**Comment by ForbodingAngel** [comment] 2017-01-20 14:17
Ok the fix PR fixed that error, but now it throws one on line 635:
`[f=-000001] Error in DrawWorldPreUnit(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:635: attempt to perform arithmetic on local 'cmdID' (a nil value)`

**Comment by ForbodingAngel** [comment] 2017-01-20 22:48
OK so following your example, after applying that PR, I did this: https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/d1f8e1df9ba70f4c4fe8569f18ed9c5e281e8492

to solve a few more errors that cropped up. However, after doing that, I get this:

`[f=0006010] Error in DrawWorld(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:662: bad argument #1 to 'Pos2BuildPos' (number expected, got nil)`

**Comment by ForbodingAngel** [comment] 2017-01-22 00:45
We're getting there! :-) When I load it up now and try to build a mex this happens:
`[f=0000228] Error in DrawWorld(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:687: attempt to compare nil with number
[f=0000228] Removed widget: Mex Placement Handler
[f=0000228] Error: DrawWorld: OpenGL stack check error, matrix mode = GL_MODELVIEW, depth = 1, please make sure to pop all matrices before end`

Additionally, The mex amounts are written vertically. I wish I could show a screenshot, but it errors before I have a chance to get it. What I'm trying to say is that it draws the spots in the right places, but the amounts given are written literally vertically xD

https://i.imgur.com/rk3l6vm.png

Edit: Placing my mouse over a mex spot with f4 view on causes the above error.

**Comment by ForbodingAngel** [comment] 2017-01-22 01:43
Your latest PR fixed the drawing and crashes, but the height (3d height) of the mex numbers was way off causing a parallax type of effect when scrolling. I fixed it here: https://github.com/Balanced-Annihilation/Balanced-Annihilation/commit/54100ad2d9c184c148821cbc51f172ed223995f7

Ok, the only 2 things that don't work atm are mex snapping and auto mex (there is no button on the UI)

**Comment by sprunk** [comment] 2017-01-22 01:46
Auto mex requires constructors to have a customparam `area_mex_def` defining which mex type to use for automex, eg
`area_mex_def = "cormex"`

**Comment by ForbodingAngel** [comment] 2017-01-22 01:49
Oh christ I'm sorry I forgot you told me that, my apologies -_-

**Comment by ForbodingAngel** [comment] 2017-01-22 02:11
Update, it all works beautifully. The only things that are "missing" are "Mex snapping" and reclaiming lower tier mexes and building higher tier ones in their place. As far as how to define the tiers of mexes, perhaps all mexes should have a customparam denoting what tier they are. Ideally the numbers of tiers would be unlimited. Perhaps instead of calling them tiers, I should just call them levels of importance. Builders trying to build a mex with a higher level of importance should reclaim any mexes of lower tier importance that are already there.

Alternatives to using customparams could be using a config, or I guess putting the importance directly in the gadget. What do you think?

**Comment by sprunk** [comment] 2017-01-22 02:18
I'd put importance in the unitdef, this way other widgets can access it.

Spring currently cannot order a building where another already resides so reclaim-and-replace would have to be two-stage. The current implementation assumes everything is resolved immediately so I'm not sure if it's easily doable without a large rewrites.

As for mex snap: #25

**Comment by ForbodingAngel** [comment] 2017-01-22 16:36
Ahh ok, well there is a mex upgrader gadget/widget combo. I'll do some work on it and have it as a companion tool. Should work out ok, I think.

So here is an interesting section of log. This is when I try to make an armmex a little ways away from a mex spot:

`[f=0003064] Metal Extractor is not a mex
[f=0003138] false
[f=0003138] Error in CommandNotify(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:401: attempt to index field '?' (a nil value)
[f=0003138] Removed widget: Mex Placement Handler`

**Comment by ForbodingAngel** [comment] 2017-01-22 16:58
When 3 builders with conflicting mex types are given an area mex command, this happens:
https://i.imgur.com/t4mewN6.png

You may or not be able to see, but a cormex was queued underneath a moho.

This only happened when I had 3 different types selected. With two is just used the moho.

**Comment by sprunk** [comment] 2017-01-22 21:41
>a cormex was queued underneath a moho.
>This only happened when I had 3 different types selected. With two is just used the moho

Weird. Currently every builder just tries building their own mex type so in both cases there's one that fails to do that.

`[f=0003138] Error in CommandNotify(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:401: attempt to index field '?' (a nil value)`

You must have made a local change because on branch `luamex` [line 401 has no code](https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/luamex/luaui/Widgets_BA/cmd_mex_placement.lua#L401).

**Comment by ForbodingAngel** [comment] 2017-01-23 01:56
> You must have made a local change because on branch luamex line 401 has no code.

You're correct. For some reason my local file didn't update even with pulling from the correct origin and git's assurances that nothing had changed.

All attempts to build a mex outside of the mex spots results in whatever mex being used "<Mexname> is not a mex".

**Comment by ForbodingAngel** [comment] 2017-01-23 02:04
Apparently I had not committed my updates to the mex list onto the remote repo yet. Sorry for the confusion. After adding more mexes to the list ( https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/685f0eb46610b7b4cc02a02b5edfef48edf5f2e6/luaui/Widgets_BA/cmd_mex_placement.lua#L400 ), this happens:

`[f=0003138] Error in CommandNotify(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:400: attempt to index field '?' (a nil value)`

**Comment by ForbodingAngel** [comment] 2017-01-23 04:38
Derp, sorry, guess I didn't realize how that table worked. Ok so mex snapping works, the first time, and then the echo errors out the second time I tried to use mex snapping:

```[f=0000151] Queueing a mex
[f=0000181] false
[f=0000181] Error in CommandNotify(): [string "LuaUI/Widgets_BA/cmd_mex_placement.lua"]:400: attempt to index field '?' (a nil value)
[f=0000181] Removed widget: Mex Placement Handler

**Comment by sprunk** [comment] 2017-01-23 05:51
Anything left to do?

**Comment by ForbodingAngel** [comment] 2017-01-23 05:58
Honestly, I don't think so. If you want to give me a hand with the mex upgrader, I would be grateful. When it tries to give the command to build the mex, it fails. The problem is that I can't see where it uses any configs or even defines tables for what mexes are upgraded from what. I was thinking that perhaps it uses extractsmetal as a basis for x replacing y, but at this moment I am stumped. It was written forever ago, so that makes it a little bit more challenging as well. There is a widget and a gadget component.

widgets/cmd_mex_upgrade_helper
gadgets/unit_mex_upgrader

Fwiw when I dump all this into the independent repo, I'll be applying proper names + docu so that it's less confusing. Atm the names tend to make little sense.

**Closed** 2017-01-24 05:35 UTC
